# Giải hệ phương trình tuyến tính

## A. Giải chính xác hệ phương trình tuyến tính
Khi thực hiện các phép toán trên số gần đúng, ta *đặc biệt* quan tâm tới 2 nguyên tắc:
* Tránh trừ 2 số gần đúng gần bằng nhau
* Tránh chia cho một số nhỏ (đặc biệt là rất nhỏ)

2 phương pháp giải hệ phương trình từ đại số:
* Phương pháp Crammes
* Phương pháp khử Gauss (phương pháp phần tử trục xoay)

**Ý tưởng**: Từ ma trận $A \cdot X = b$ ta đưa về ma trận $C \cdot X = b'$ với $C$ là ma trận tam giác trên.



Giả sử có ta có hệ phương trình với các phương trình như sau
$$(E_k): \sum_{i=0}^n a_{ki} x_{i} = b_k, 1 \le k \le n$$

Chuyển về ma trận
$$
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots  & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}\\
\end{bmatrix} \cdot \begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n \\
\end{bmatrix} = \begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_n \\
\end{bmatrix}
$$
$$rank(A) = rank(\bar{A})$$

Quá trình thuận:
* **Bước 1:** Nếu $|a_{k1}| = \max |a_{i1}|$ thì ta đổi chỗ hàng $k$ lên đầu và thay hàng đầu xuống. Sau đó khử tất cả các hệ số của $x_1$ trong các phương trình $(E_i), i \ge 2$
* **Bước 2:** Nếu $|a_{s2}| = \max |a_{i2}|$ thì ta đổi chỗ hàng $s$ lên hàng 2. Sau đó khử tất cả các hệ số của $x_2$ trong các phương trình $(E_i), i \ge 3$ .
* ...

Tiếp tục lặp như vậy cho tới khi nhận được ma trận *tam giác trên*.

Quá trình ngược:
* **Trường hợp 1**: Tất cả các hàng trong ma trận tam giác trên đều $\ne 0$.
    * Khi đó ta giải được luôn
      $$x_n = \frac{b^{(n-1)}_{n}}{a^{(n-1)}_{nn}}.$$
    * Thay giá trị $x_n$ vào phương trình và làm tương tự cho tới khi tìm được tất cả $x_i, (i = \overline{1,...,n}).$
* **Trường hợp 2**: Ta có $k$ hàng $0$ và $rank(A) = rank(\bar{A})$.
    * Khi đó ta đặt $x_n = t_1, x_{n-1} = t_2,...,x_{n-k+1} = t_k$, với $t_i \in \mathbb{R}$ tuỳ ý.
    * Ta chuyển các số hạng có $t_i$ sáng vế phải và nhận được hệ phương trình có $(n-k)$ phương trình với $(n-k)$ ẩn và tất cả phần tử trên đường chéo chính $\ne 0$.
    * Tiếp tục giải như trường hợp 1.





In [5]:
import numpy as np
def g_(a, b):
    return b - b[0] / a[0] * a
a = np.array([35, 1, -1, 38])
b = np.array([2, 3, -50, -130])
print(g_(a, b))

[   0.            2.94285714  -49.94285714 -132.17142857]


## B. Phân tích ma trận


### Phương pháp phân tích LU
Giả thiết:
$$
A = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & \ddots  & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}\\
\end{bmatrix}
$$

Cần xây dựng ma trận $L$ và $U$: $L$ là ma trận tam giác trên, $U$ là ma trận tam giác dưới

$$
L = \begin{bmatrix}
1 & 0 & \cdots & 0 \\
l_{21} & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots  & \vdots \\
l_{n1} & l_{n2} & \cdots & 1\\
\end{bmatrix}
$$

$$
U = \begin{bmatrix}
u_{11} & u_{12} & \cdots & u_{1n}\\
0 & u_{22} & \cdots & u_{2n}\\
\vdots & \vdots & \ddots  & \vdots \\
0 & 0 & \cdots & u_{nn}\\
\end{bmatrix}
$$

* **Bước 1:** Chọn $l_{11}$ và $u_{11}$ để thoả mãn $l_{11} u_{11} = a_{11}$. Nếu $l_{11} u_{11} = 0$ thì không thể phân tích.
* **Bước 2:** Với $j=2,...,n$ đặt:
$$u_{1j} = \frac{a_{1j}}{l_{11}},$$
$$l_{j1} = \frac{a_{j1}}{u_{11}}.$$
* **Bước 3:** Với $i=2,...,n-1$ thực hiện:
    * **Bước 4:** Chọn $l_{ii}$ và $u_{ii}$ thoả mãn
$$l_{ii}u_{ii} = a_{ii} - \sum_{k=1}^{i-1}l_{ik}u_{ki}.$$
Nếu  $l_{ii}u_{ii} =  0$ thì không thể phân tích.

    * **Bước 5:** Với $j=i+1,...,n$ thực hiện
$$u_{ij} = \frac{1}{l_{ii}} [a_{ij} - \sum_{k=1}^{i-1}l_{ik}u_{kj}],$$
$$l_{ji} = \frac{1}{u_{ii}} [a_{ji} - \sum_{k=1}^{i-1}l_{jk}u_{ki}].$$

* **Bước 6:** Chọn $l_{nn}$ và $u_{nn}$ thoả mãn:
$$l_{nn} u_{nn} = a_{nn} - \sum_{k=1}^{n-1}l_{nk}u_{kn}.$$


#### Ví dụ
*Ví dụ:* Phân tích ma trận sau

$$
A = \begin{bmatrix}
2 & 1 & 2 \\
-2 & 2 & 1 \\
1 & 2 & -2 \\
\end{bmatrix}
$$

Ta đặt
$$
L = \begin{bmatrix}
1 &  0 & 0 \\
l_{21} & 1 & 0 \\
l_{31} & l_{32} & 1 \\
\end{bmatrix}
$$
$$
U = \begin{bmatrix}
u_{11} &  u_{12} & u_{13} \\
0 & u_{22} & u_{23} \\
0 & 0 & u_{33} \\
\end{bmatrix}
$$

**Bước 1:** $u_{11} = 2$

**Bước 2:** 

$$u_{12} = 1, u_{13} = 2$$
$$l_{21} = -1, l_{31} = 0.5$$


**Bước 3:**
$$u_{22} =  a_{22} - l_{21}u_{12} = 3$$
$$u_{23} = a_{23} - l_{21}u_{13} = 3$$
$$l_{32} = \frac{1}{u_{33}}(a_{32} - l_{31}u_{12}) = 0.5$$
$$u_{33} =  a_{33} - l_{31}u_{13} - l_{32}u_{23} = -4.5$$

Như vậy ta được ma trận
$$A = LU = \begin{bmatrix}
1 & 0 & 0 \\
-1 & 1 & 0 \\
0.5 & 0.5 & 1\\
\end{bmatrix} \cdot \begin{bmatrix}
2 & 1 & 2 \\
0 & 3 & 3 \\
0 & 0 & -4.5 \\
\end{bmatrix}$$

In [9]:
from numpy import array
from scipy.linalg import lu

a = array([[0.00651, 26., 2.],[35., 1., -1.],[2., 3., -51.]])
np.set_printoptions(suppress=True)
pl, u = lu(a, permute_l=True)

In [10]:
u

array([[ 35.        ,   1.        ,  -1.        ],
       [  0.        ,  25.999814  ,   2.000186  ],
       [  0.        ,   0.        , -51.16925344]])

In [11]:
pl

array([[0.000186  , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.05714286, 0.11318762, 1.        ]])

In [12]:
u @ pl

array([[  0.94936714,  34.88681238,  -1.        ],
       [ 26.11411034,   0.2263963 ,   2.000186  ],
       [ -2.92395734,  -5.79172616, -51.16925344]])

### Áp dụng phương pháp phân tích LU để giải hệ phương trình
Với $A=LU$, ta có thể sử dụng để giải hệ phương trình $Ax = b$ như sau:
$$LUx=b$$
$$Ux = L^{-1}b$$
$$x = U^{-1}(L^{-1}b).$$

Như vậy, ta có thể chuyển bài toán tìm x về tìm $y$ thoả mãn $Ly = b$ và $x$ sẽ là nghiệm của phương trình $Ux=y$.

In [7]:
def forward_sub(L, b):
    """x = forward_sub(L, b) is the solution to L x = b
       L must be a lower-triangular matrix
       b must be a vector of the same leading dimension as L
    """
    n = L.shape[0]
    x = np.zeros(n)
    for i in range(n):
        tmp = b[i]
        for j in range(i-1):
            tmp -= L[i,j] * x[j]
        x[i] = tmp / L[i,i]
    return x
def back_sub(U, b):
    """x = back_sub(U, b) is the solution to U x = b
       U must be an upper-triangular matrix
       b must be a vector of the same leading dimension as U
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        tmp = b[i]
        for j in range(i+1, n):
            tmp -= U[i,j] * x[j]
        x[i] = tmp / U[i,i]
    return x
def lu_solve(L, U, b):
    """x = lu_solve(L, U, b) is the solution to L U x = b
       L must be a lower-triangular matrix
       U must be an upper-triangular matrix of the same size as L
       b must be a vector of the same leading dimension as L
    """
    y = forward_sub(L, b)
    x = back_sub(U, y)
    return x